name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        architecture:
          - x64

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure
      run: make setup
      
    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version: 2.0.0
        
    - name: Install dependencies
      run: sudo apt install libgtk-4-dev libfuse2 build-essential
      
    - name: Install Nim dependencies
      run: nimble install owlkettle@#head -y
      
    - name: Install appimagetool
      run: |
        wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        chmod a+x appimagetool-x86_64.AppImage
        sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
        
    - name: Build Appimage
      run: make appimage

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: Libre_Path_Adder-x86_64.AppImage
