name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: make setup
      
    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.1.4
      with:
        nim-version: 2.0.0
        
    - name: Install dependencies
      run: sudo apt install libgtk-4-1

    - name: Build
      run: make release
