name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: make setup

    - name: Install dependencies
      run: sudo apt install libgtk-4-1 && curl https://nim-lang.org/choosenim/init.sh -sSf | sh

    - name: Build
      run: make release
